// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDExIY_yRA8NYYbKLcnYlPaiZ9xUvlGTbs',
    appId: '1:517738953680:web:a37906d4b130161d1c17d5',
    messagingSenderId: '517738953680',
    projectId: 'media-network-9315c',
    authDomain: 'media-network-9315c.firebaseapp.com',
    storageBucket: 'media-network-9315c.firebasestorage.app',
    measurementId: 'G-70Z06013Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk3UWOv3UkNFJ6Lx_KsKgB6k41bf3otYo',
    appId: '1:517738953680:android:3239b408c90710411c17d5',
    messagingSenderId: '517738953680',
    projectId: 'media-network-9315c',
    storageBucket: 'media-network-9315c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9dMglR51bCRr6PMZH0YMEX9Peze3eYN8',
    appId: '1:517738953680:ios:5880a0c019283dd11c17d5',
    messagingSenderId: '517738953680',
    projectId: 'media-network-9315c',
    storageBucket: 'media-network-9315c.firebasestorage.app',
    iosBundleId: 'com.example.mediaNetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9dMglR51bCRr6PMZH0YMEX9Peze3eYN8',
    appId: '1:517738953680:ios:5880a0c019283dd11c17d5',
    messagingSenderId: '517738953680',
    projectId: 'media-network-9315c',
    storageBucket: 'media-network-9315c.firebasestorage.app',
    iosBundleId: 'com.example.mediaNetwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDExIY_yRA8NYYbKLcnYlPaiZ9xUvlGTbs',
    appId: '1:517738953680:web:ee64abd61b5f99f11c17d5',
    messagingSenderId: '517738953680',
    projectId: 'media-network-9315c',
    authDomain: 'media-network-9315c.firebaseapp.com',
    storageBucket: 'media-network-9315c.firebasestorage.app',
    measurementId: 'G-WXFGNLM9EY',
  );
}
