final List<String> skills = [
  "Graphics Design",
  "Motion Graphics",
  "Video Editing",
  "Cinematography",
  "Photography",
  "Photo Editing",
  "Content Writing",
  "Copywriting",
  "Script Writing",
  "Social Media Management",
  "Digital Marketing",
  "Live Streaming",
  "Audio Production",
  "Podcast Production",
  "Sound Engineering",
  "Voice Over",
  "UI/UX Design",
  "Web Design",
  "Animation",
  "Brand Design",
  "Drone Videography",
  "Lighting & Set Design",
  "Photography Direction",
  "Video Directing",
  "Creative Direction",
  "Other",
];

final List<String> nationalities = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",

  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",

  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",

  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",

  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",

  "Fiji",
  "Finland",
  "France",

  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",

  "Haiti",
  "Honduras",
  "Hungary",

  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",

  "Jamaica",
  "Japan",
  "Jordan",

  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",

  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",

  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",

  "Namibia",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",

  "Oman",

  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",

  "Qatar",

  "Romania",
  "Russia",
  "Rwanda",

  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",

  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",

  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",

  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",

  "Yemen",

  "Zambia",
  "Zimbabwe",
];

final List<String> titles = [
  "Pastor",
  "Deacon",
  "Deaconess",
  "Brother",
  "Sister",
];

final List<Map<String, String>> countryCodes = [
  {"code": "+1", "name": "United States / Canada"},
  {"code": "+7", "name": "Russia / Kazakhstan"},
  {"code": "+20", "name": "Egypt"},
  {"code": "+27", "name": "South Africa"},
  {"code": "+30", "name": "Greece"},
  {"code": "+31", "name": "Netherlands"},
  {"code": "+32", "name": "Belgium"},
  {"code": "+33", "name": "France"},
  {"code": "+34", "name": "Spain"},
  {"code": "+36", "name": "Hungary"},
  {"code": "+39", "name": "Italy"},
  {"code": "+40", "name": "Romania"},
  {"code": "+41", "name": "Switzerland"},
  {"code": "+43", "name": "Austria"},
  {"code": "+44", "name": "United Kingdom"},
  {"code": "+45", "name": "Denmark"},
  {"code": "+46", "name": "Sweden"},
  {"code": "+47", "name": "Norway"},
  {"code": "+48", "name": "Poland"},
  {"code": "+49", "name": "Germany"},

  {"code": "+52", "name": "Mexico"},
  {"code": "+55", "name": "Brazil"},
  {"code": "+56", "name": "Chile"},
  {"code": "+57", "name": "Colombia"},
  {"code": "+58", "name": "Venezuela"},

  {"code": "+60", "name": "Malaysia"},
  {"code": "+61", "name": "Australia"},
  {"code": "+62", "name": "Indonesia"},
  {"code": "+63", "name": "Philippines"},
  {"code": "+64", "name": "New Zealand"},
  {"code": "+65", "name": "Singapore"},
  {"code": "+66", "name": "Thailand"},

  {"code": "+81", "name": "Japan"},
  {"code": "+82", "name": "South Korea"},
  {"code": "+84", "name": "Vietnam"},
  {"code": "+86", "name": "China"},
  {"code": "+90", "name": "Turkey"},

  {"code": "+92", "name": "Pakistan"},
  {"code": "+93", "name": "Afghanistan"},
  {"code": "+94", "name": "Sri Lanka"},
  {"code": "+95", "name": "Myanmar"},
  {"code": "+98", "name": "Iran"},

  {"code": "+234", "name": "Nigeria"},
  {"code": "+233", "name": "Ghana"},
  {"code": "+237", "name": "Cameroon"},
  {"code": "+251", "name": "Ethiopia"},
  {"code": "+254", "name": "Kenya"},
  {"code": "+255", "name": "Tanzania"},
  {"code": "+256", "name": "Uganda"},
  {"code": "+258", "name": "Mozambique"},
  {"code": "+260", "name": "Zambia"},
  {"code": "+263", "name": "Zimbabwe"},
];
